<a href="https://colab.research.google.com/github/prashanth-ds-ml/Projects/blob/main/spam_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/spam.csv',encoding = 'ISO-8859-1')

In [3]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [6]:
df.shape

(5572, 5)

In [7]:
df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'], axis=1,inplace = True)

In [8]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.rename(columns = {'v1':'Label','v2':'Messsage'}, inplace = True)

In [10]:
df.head()

Label                                           Messsage
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
import re

def cleaning_text(text):
  text = re.sub('[^a-zA-Z]', ' ', text)
  text = re.sub('<.*?>','',text)
  text = re.sub('[^\w\d\s]','',text)
  text = re.sub('^\s+|\s+?$','',text)
  return text

In [12]:
clean_messages = df['Messsage'].apply(func=cleaning_text)
clean_messages.head()

0    Go until jurong point  crazy   Available only ...
1                           Ok lar    Joking wif u oni
2    Free entry in   a wkly comp to win FA Cup fina...
3       U dun say so early hor    U c already then say
4    Nah I don t think he goes to usf  he lives aro...
Name: Messsage, dtype: object

In [13]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
import nltk
from nltk.corpus import stopwords
stopwords = nltk.corpus.stopwords.words("english")
clean_messages =clean_messages.apply(lambda x: ' '.join(word for word in x.split() if word not in stopwords))
clean_messages

0       Go jurong point crazy Available bugis n great ...
1                                 Ok lar Joking wif u oni
2       Free entry wkly comp win FA Cup final tkts st ...
3                     U dun say early hor U c already say
4                Nah I think goes usf lives around though
                              ...                        
5567    This nd time tried contact u U Pound prize cla...
5568                       Will b going esplanade fr home
5569                             Pity mood So suggestions
5570    The guy bitching I acted like interested buyin...
5571                                   Rofl Its true name
Name: Messsage, Length: 5572, dtype: object

In [15]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [16]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [17]:
from nltk.stem import WordNetLemmatizer

wn_lemmatizer = WordNetLemmatizer()
clean_messages = clean_messages.apply(lambda x: ' '.join(wn_lemmatizer.lemmatize(word) for word in x.split()))

clean_messages

0       Go jurong point crazy Available bugis n great ...
1                                 Ok lar Joking wif u oni
2       Free entry wkly comp win FA Cup final tkts st ...
3                     U dun say early hor U c already say
4                   Nah I think go usf life around though
                              ...                        
5567    This nd time tried contact u U Pound prize cla...
5568                       Will b going esplanade fr home
5569                              Pity mood So suggestion
5570    The guy bitching I acted like interested buyin...
5571                                   Rofl Its true name
Name: Messsage, Length: 5572, dtype: object

In [18]:
import matplotlib.pyplot as plt
from wordcloud import WordCloud

wordcloud = WordCloud(width=600, 
                     height=400, 
                     random_state=2, 
                     max_font_size=100).generate(str(clean_messages))

plt.figure(figsize=(10, 7))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

In [19]:
labels = df['Label']

In [20]:
labels = pd.get_dummies(labels, columns=['Label'])

In [21]:
labels.drop(['ham'], axis=1,inplace = True)

In [22]:
labels.head()

spam
0     0
1     0
2     1
3     0
4     0

In [23]:
labels.rename(columns = {'spam':'Label'}, inplace = True)

In [24]:
labels

Label
0         0
1         0
2         1
3         0
4         0
...     ...
5567      1
5568      0
5569      0
5570      0
5571      0

[5572 rows x 1 columns]

In [25]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(clean_messages, labels, test_size=0.25, random_state=10)

In [26]:
print(f'shape of x_train :{x_train.shape}')
print(f'shape of x_test :{x_test.shape}')
print(f'shape of y_train :{y_train.shape}')
print(f'shape of y_test :{y_test.shape}')

shape of x_train :(4179,)
shape of x_test :(1393,)
shape of y_train :(4179, 1)
shape of y_test :(1393, 1)


In [27]:
y_train = np.squeeze(y_train)

In [28]:
y_test = np.squeeze(y_test)

In [29]:
y_test.head()

4635    0
2279    0
4545    0
5084    0
5298    0
Name: Label, dtype: uint8

In [30]:
print(f'shape of y_train :{y_train.shape}')
print(f'shape of y_test :{y_test.shape}')

shape of y_train :(4179,)
shape of y_test :(1393,)


In [31]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [32]:
tokenize = Tokenizer(num_words=10000)

tokenize.fit_on_texts(x_train)

x_train = tokenize.texts_to_sequences(x_train)
x_test = tokenize.texts_to_sequences(x_test)

In [33]:
print(tokenize.word_index)

{'i': 1, 'u': 2, 'call': 3, 'get': 4, 'ur': 5, 'you': 6, 'go': 7, 'gt': 8, 'lt': 9, 'free': 10, 'day': 11, 'ok': 12, 'know': 13, 'come': 14, 'time': 15, 'got': 16, 'like': 17, 'good': 18, 'no': 19, 'want': 20, 'love': 21, 'text': 22, 'txt': 23, 'p': 24, 'send': 25, 'one': 26, 'need': 27, 'r': 28, 'home': 29, 'going': 30, 'how': 31, 'stop': 32, 'n': 33, 'take': 34, 'today': 35, 'k': 36, 'lor': 37, 'if': 38, 'but': 39, 'dont': 40, 'tell': 41, 'still': 42, 'reply': 43, 'da': 44, 'sorry': 45, 'mobile': 46, 'see': 47, 'back': 48, 'we': 49, 'week': 50, 'so': 51, 'phone': 52, 'think': 53, 'hi': 54, 'what': 55, 'later': 56, 'msg': 57, 'new': 58, 'the': 59, 'do': 60, 'much': 61, 'pls': 62, 'please': 63, 'it': 64, 'min': 65, 'just': 66, 'well': 67, 'oh': 68, 'dear': 69, 'thing': 70, 'c': 71, 'a': 72, 'great': 73, 'your': 74, 'night': 75, 'co': 76, 'make': 77, 'my': 78, 'message': 79, 'and': 80, 'hope': 81, 'claim': 82, 'say': 83, 'hey': 84, 'work': 85, 'b': 86, 'now': 87, 'have': 88, 'yes': 89, 

In [34]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [35]:
pad_length = 200

size = len(tokenize.word_index) + 1
print(size)

6367


In [36]:
x_train = pad_sequences(x_train, padding='pre', maxlen=pad_length)
x_test = pad_sequences(x_test, padding='pre', maxlen=pad_length)

print(x_train,'\n')
print(x_test)

[[   0    0    0 ... 2154 3141  146]
 [   0    0    0 ... 3142 2155 1232]
 [   0    0    0 ...   94    5   29]
 ...
 [   0    0    0 ... 1174  901 6363]
 [   0    0    0 ...  251  324  120]
 [   0    0    0 ... 6365 6366  192]] 

[[   0    0    0 ...  484  255 1094]
 [   0    0    0 ...    3   56  267]
 [   0    0    0 ...   96 1354  675]
 ...
 [   0    0    0 ...   91  410    2]
 [   0    0    0 ...   99   58  211]
 [   0    0    0 ...  379  729   29]]


In [37]:
#!wget -N http://nlp.stanford.edu/data/glove.6B.zip

In [38]:
#!unzip -n glove.6B.zip

In [39]:
glove_300 = pd.read_csv('glove.6B.300d.txt', sep=" ", quoting=3, header=None, index_col=0)

In [40]:
glove_300.head()

1         2         3         4         5         6         7    \
0                                                                           
the  0.046560  0.213180 -0.007436 -0.458540 -0.035639  0.236430 -0.288360   
,   -0.255390 -0.257230  0.131690 -0.042688  0.218170 -0.022702 -0.178540   
.   -0.125590  0.013630  0.103060 -0.101230  0.098128  0.136270 -0.107210   
of  -0.076947 -0.021211  0.212710 -0.722320 -0.139880 -0.122340 -0.175210   
to  -0.257560 -0.057132 -0.671900 -0.380820 -0.364210 -0.082155 -0.010955   

          8         9       10   ...       291       292       293       294  \
0                                ...                                           
the  0.215210 -0.134860 -1.6413  ... -0.013064 -0.296860 -0.079913  0.195000   
,    0.107560  0.058936 -1.3854  ...  0.075968 -0.014359 -0.073794  0.221760   
.    0.236970  0.328700 -1.6785  ...  0.060148 -0.156190 -0.119490  0.234450   
of   0.121370 -0.070866 -1.5721  ... -0.366730 -0.386030  0.302900  0.015747   
to  -0.082047  0.460560 -1.8477  ... -0.012806 -0.597070  0.317340 -0.252670   

          295       296       297       298       299       300  
0                                                                
the  0.031549  0.285060 -0.087461  0.009061 -0.209890  0.053913  
,    0.146520  0.566860  0.053307 -0.232900 -0.122260  0.354990  
.    0.081367  0.246180 -0.152420 -0.342240 -0.022394  0.136840  
of   0.340360  0.478410  0.068617  0.183510 -0.291830 -0.046533  
to   0.543840  0.063007 -0.049795 -0.160430  0.046744 -0.070621  

[5 rows x 300 columns]

In [41]:
print(glove_300.index.values.take(list(range(0, 100, 10))))
print(glove_300.index.values[:10])

['the' 'for' 'it' 'be' 'had' 'new' 'up' "n't" '$' 'president']
['the' ',' '.' 'of' 'to' 'and' 'in' 'a' '"' "'s"]


In [42]:
embeddings_dictionary = {key: val.values for key, val in glove_300.T.items()}

In [43]:
embeddings_dictionary['president']

array([ 4.3665e-01,  1.8793e-01, -1.7022e-01, -1.0869e-01,  1.9476e-01,
       -2.4502e-01, -7.7660e-01, -2.5813e-01,  4.3630e-01, -2.0884e+00,
       -9.6794e-03,  1.4941e-01,  7.2166e-02, -6.5154e-01, -3.0189e-01,
        8.5747e-01, -3.1906e-02, -4.5204e-01,  8.4932e-02, -4.1816e-01,
        2.6820e-01, -4.5985e-02,  8.0586e-01, -1.3507e-01, -4.7616e-01,
        1.4891e-01,  2.3255e-01,  3.2640e-01,  2.1525e-01, -4.9949e-01,
        4.6968e-01,  1.5521e-01,  4.8574e-01,  3.3412e-01, -1.4695e+00,
        6.2657e-02,  1.9865e-01, -2.9627e-01, -3.4174e-02, -3.9326e-01,
        4.5055e-02,  2.7545e-01, -2.3320e-01, -4.9622e-02, -3.3297e-01,
       -4.0912e-01, -2.4932e-01, -3.8237e-01,  8.8357e-02, -3.8397e-01,
       -2.0878e-01,  1.2368e-03,  3.4651e-01,  1.0924e+00,  5.1525e-01,
        2.9204e-01, -2.0349e-01,  4.0670e-01,  7.7727e-01, -7.7313e-02,
       -2.3235e-02,  1.2527e-01,  4.2712e-01, -2.3133e-01,  4.2311e-01,
       -4.6994e-01, -3.7960e-01,  6.0969e-01, -3.7170e-01, -1.31

In [44]:
embeddings_matrix = np.zeros((size, 300))

for word, index in tokenize.word_index.items():
  emb_vector = embeddings_dictionary.get(word)
  if emb_vector is not None:
    embeddings_matrix[index] = emb_vector
     


In [45]:
embeddings_matrix.shape

(6367, 300)

In [46]:
embeddings_matrix[0].shape

(300,)

In [47]:
embeddings_matrix[:5]

array([[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [-0.13292 ,  0.16985 , -0.1436  , ..., -0.23778 ,  0.14766 ,
         0.62902 ],
       [ 0.016393, -0.40067 , -0.26541 , ..., -0.63718 , -0.066708,
         0.35212 ],
       [ 0.048021,  0.13645 , -0.33734 , ..., -0.27052 , -0.12922 ,
        -0.013268],
       [-0.14124 , -0.11836 , -0.30782 , ..., -0.19883 , -0.061105,
         0.11568 ]])

In [48]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim = size, output_dim = 300,
                              weights=[embeddings_matrix],input_length=pad_length,
                              trainable=False),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(rate=0.8),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(rate=0.5),
    tf.keras.layers.Dense(18, activation='tanh'),
    tf.keras.layers.Dropout(rate=0.3),
    tf.keras.layers.Dense(6, activation='tanh'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [49]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [50]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 200, 300)          1910100   
                                                                 
 global_average_pooling1d (G  (None, 300)              0         
 lobalAveragePooling1D)                                          
                                                                 
 dense (Dense)               (None, 64)                19264     
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                        

In [51]:
history = model.fit(x_train,y_train,batch_size=128,epochs=30,validation_split=0.30)

Epoch 1/30
23/23 [==============================] - 2s 25ms/step - loss: 0.6442 - accuracy: 0.8058 - val_loss: 0.5630 - val_accuracy: 0.8756
Epoch 2/30
23/23 [==============================] - 0s 5ms/step - loss: 0.4872 - accuracy: 0.8636 - val_loss: 0.3764 - val_accuracy: 0.8756
Epoch 3/30
23/23 [==============================] - 0s 5ms/step - loss: 0.3806 - accuracy: 0.8639 - val_loss: 0.2945 - val_accuracy: 0.8756
Epoch 4/30
23/23 [==============================] - 0s 5ms/step - loss: 0.3180 - accuracy: 0.8715 - val_loss: 0.2120 - val_accuracy: 0.8907
Epoch 5/30
23/23 [==============================] - 0s 6ms/step - loss: 0.2482 - accuracy: 0.8964 - val_loss: 0.1487 - val_accuracy: 0.9649
Epoch 6/30
23/23 [==============================] - 0s 5ms/step - loss: 0.1973 - accuracy: 0.9299 - val_loss: 0.1113 - val_accuracy: 0.9705
Epoch 7/30
23/23 [==============================] - 0s 6ms/step - loss: 0.1682 - accuracy: 0.9456 - val_loss: 0.0984 - val_accuracy: 0.9721
Epoch 8/30
23/23 [=

In [52]:
fig = plt.figure(figsize=(10, 4))
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Accuracy of Model')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(['train', 'test'], loc='lower right')
plt.show()

In [53]:
fig = plt.figure(figsize=(10, 4))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Loss of Model')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend(['train', 'test'], loc='upper right')
plt.show()
